---
version: "3"

networks:
  mccnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  team2data:
    build: ./team2project/.
    image: team2data:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - API_HOST=team2auth:8081
    networks:
      mccnetwork:
        ipv4_address: 172.20.0.2

  team2auth:
    build: ./team2project-auth/.
    image: team2auth:latest
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      - API_HOST=team2data:8080
    networks:
      mccnetwork:
        ipv4_address: 172.20.0.3


  front_end:
    build: ./team2foxreactday6/.
    image: front_end:latest
    environment:
      - API_HOST_ENV=team2data:8080
      - AUTH_HOST_ENV=team2auth:8081
    ports:
      - 3000:80
    networks:
      mccnetwork:
        ipv4_address: 172.20.0.4








